"""Frozen parameters for A144 v4 with candidate replacement."""

ACCOUNT = "8890145315"
STRATEGY_NAME = "RedisQMT_A144_v4"
ORDER_REMARK_PREFIX = "A144V4"
BENCHMARK = "000905.SH"
SECTOR = "中证500"

INITIAL_RESEARCH_ANCHOR = "20220104"
HISTORY_BARS = 150
HISTORY_CHUNK_SIZE = 40
HISTORY_TIMEOUT_SECONDS = 30
FACTOR_WINDOW = 20
FACTOR_TOP_PCT = 0.15
REFRESH_INTERVAL = 10

BREAKOUT_PERIOD = 10
BREAKOUT_STRENGTH_PCT = 0.005
VOL_RATIO_MIN = 1.20
VOL_LOOKBACK = 5
MA_STOCK = 20
MA_SLOPE_PERIOD = 5
MOMENTUM_DAYS = 3
MOMENTUM_UP_MIN = 2
GAP_HISTORY_DAYS = 60
GAP_HISTORY_MAX_PCT = -0.07
MAX_CONSECUTIVE_UP = 3
RECENT_RANGE_DAYS = 5
MAX_RECENT_RANGE_PCT = 0.10
GAP_DOWN_PCT = -0.03

MAX_HOLD_BARS = 20
HARD_STOP_PCT = -0.18
EARLY_STOP_PCT = -0.12
EARLY_STOP_DAYS = 3
WEAK_EXIT_MIN_BARS = 12
WEAK_EXIT_MAX_RETURN = -0.04
WEAK_EXIT_RESERVE_SLOT = True
ALL_SELL_COOLDOWN = 30
STOP_COOLDOWN = 60

MAX_POSITIONS = 5
MAX_NEW_ENTRIES_PER_DAY = 2
TRADE_LOT_SIZE = 100
MIN_DAILY_AMOUNT = 3e7
MIN_HISTORY_BARS = 130

MARKET_MA = 20
MARKET_FILTER_PCT = 0.03

RISK_BUDGET_SCALE = 1.0
RISK_MULTIPLIER_MIN = 0.65
RISK_MULTIPLIER_MAX = 1.35

# Reverse-T entry and normal buyback.  Emergency/forced original buybacks are
# deliberately absent in v4.
DAYT_SELL_FRACTION = 0.60
DAYT_ATR_PERIOD = 14
DAYT_SELL_ATR_MULT = 0.40
DAYT_SELL_RISE_MIN_PCT = 0.012
DAYT_SELL_RISE_MAX_PCT = 0.040
DAYT_ARM_MIN_SAMPLES = 2
DAYT_ARM_EXTENSION_PCT = 0.0015
DAYT_SELL_PULLBACK_PCT = 0.0020
DAYT_BUYBACK_ATR_MULT = 0.15
DAYT_BUYBACK_MIN_PCT = 0.006
DAYT_BUYBACK_MAX_PCT = 0.020
DAYT_BUYBACK_BOUNCE_PCT = 0.0010
DAYT_NEW_SELL_CUTOFF = "14:20:00"
DAYT_REPLACEMENT_PREPARE_TIME = "14:40:00"
DAYT_REPLACEMENT_TIME = "14:50:00"
DAYT_REPLACEMENT_CASH_USAGE = 0.98
DAYT_REPLACEMENT_POOL_LIMIT = 20
DAYT_POLL_SECONDS = 3.0
DAYT_HISTORY_BARS = 40
DAYT_MAX_CYCLES_PER_SYMBOL = 1

# Production gate.  The daily A144 strategy may execute live, while the
# reverse-T/replacement overlay remains signal-only until strict minute and
# continuous-account validation passes.
DAYT_LIVE_ENABLED = False
